### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by c0d3rman** [c0d3rman/Pokemon-Metronome-Battle-Analysis#1]
## Improvements
- [ ] Don't write unnecessary teammate entries in meta explorer (ones that are [1, 1])
- [ ] Add scheduler into meta explorer
- [ ] Deduplicate meta explorer and move counter
- [ ] Allow selecting matchup in move counter
- [ ] Add arg validation
- [ ] Add team length validation
- [ ] Fix all special case moves in analysis
- [ ] Add usage message with [command-line-usage](https://github.com/75lb/command-line-usage)

## New Features
- [ ] Breakdown what kills pokemon / what deals the most damage overall in a fight
- [ ] AI for when to dyna?
- [ ]  Abstract away input of teams - can input a list of predefined teams, or a meta-file (or meta explorer output file) to randomly generate teams from. Maybe a team generator?
- [ ] #2
- [ ] Add proper build toolchain
- [ ] Look into expanding to other modes

## Analysis
- [ ] Calculate winrate variance using binomial distribution
- [ ] Document decisionmaking - begin some sorta research diary
- [ ] Finish ability tierlist (back it with data)
- [ ] Finish item tierlist
- [ ] Test if being paralyzed hurts or helps
- [ ] Check if STAB actually helps by manually nerfing it
- [ ] Deal with varying attack stat in %HP damage calculation
- [ ] List all moves affected by Bulletproof, Soundproof etc.

## Done
- [x] Add comprehensive average %HP damage analysis to defensive analysis
- [x] Make a new meta_teams file
- [x] Fix guzz teams str warning
- [x] Refactor util into multiple files
